---
language: ruby
sudo: false
cache:
  - bundler
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.4
  - 2.3.1
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
script: bundle exec rake spec
