---
before_install:
  - gem update --system
  - gem install bundler -v "~> 2.0"
language: ruby
sudo: false
cache:
  - bundler
rvm:
  - 2.5
  - 2.6
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
script: bundle exec rake spec
